/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CFab: typeof import('./components/fab/CFab.vue')['default']
    CNavigationRail: typeof import('./components/navigation-rail/CNavigationRail.vue')['default']
    CNavigationRailItem: typeof import('./components/navigation-rail/CNavigationRailItem.vue')['default']
    CollectionPage: typeof import('./pages/collection/collection-page/CollectionPage.vue')['default']
    CSearchBar: typeof import('./components/search-bar/CSearchBar.vue')['default']
    SearchFilters: typeof import('./views/search-view/search-filters/SearchFilters.vue')['default']
    SearchInput: typeof import('./views/search-view/search-input/SearchInput.vue')['default']
    SearchPage: typeof import('./pages/search/search-page/SearchPage.vue')['default']
    SearchView: typeof import('./views/search-view/SearchView.vue')['default']
  }
}
